/**
 * @togglebox/configs
 *
 * Zod schemas and TypeScript types for remote configuration management (Tier 1).
 *
 * @remarks
 * All schemas are used for validating HTTP request/response payloads and database operations.
 * TypeScript types are automatically inferred from Zod schemas using z.infer<>.
 */

import { z } from 'zod';

/**
 * Schema for configuration JSON objects.
 *
 * @remarks
 * Accepts a flexible key-value structure where values can be:
 * - string
 * - number
 * - boolean
 * - nested objects (passthrough allows any structure)
 *
 * No enforced schema - applications define their own configuration structure.
 * Size limit: 300KB (to stay within DynamoDB 400KB item limit with metadata).
 *
 * @example
 * ```ts
 * // Valid configuration examples
 * const config1 = {
 *   apiUrl: 'https://api.example.com',
 *   timeout: 5000,
 *   enableLogging: true,
 * };
 *
 * const config2 = {
 *   api: {
 *     baseUrl: 'https://api.example.com',
 *     endpoints: {
 *       users: '/v1/users',
 *       posts: '/v1/posts',
 *     },
 *   },
 *   features: {
 *     darkMode: true,
 *     analytics: false,
 *   },
 *   limits: {
 *     maxRequests: 1000,
 *     rateLimit: 100,
 *   },
 * };
 *
 * // Validate config
 * ConfigSchema.parse(config1); // ✅ Valid
 * ConfigSchema.parse(config2); // ✅ Valid
 *
 * // Size limit validation
 * const tooLarge = { data: 'x'.repeat(350_000) };
 * ConfigSchema.parse(tooLarge); // ❌ Throws: "Config size exceeds 300KB limit"
 * ```
 */
export const ConfigSchema = z.record(
  z.string(),
  z.union([z.string(), z.number(), z.boolean(), z.object({}).passthrough()])
).refine(
  (config) => JSON.stringify(config).length < 300_000,
  { message: 'Config size exceeds 300KB limit (DynamoDB constraint)' }
);

/**
 * Schema for configuration version objects.
 *
 * @remarks
 * Represents an immutable versioned configuration within an environment.
 * Versions are identified by versionLabel (semantic version) for human-readable URLs.
 *
 * **Fields:**
 * - platform: Application/service identifier
 * - environment: Deployment environment (e.g., "production", "staging")
 * - versionLabel: Semantic version identifier (e.g., "1.0.0", "2.1.0") - PRIMARY KEY for lookups
 * - versionTimestamp: Auto-generated ISO-8601 timestamp for audit trail
 * - isStable: Flag indicating production-ready status
 * - config: Arbitrary JSON configuration data (max 300KB)
 * - createdBy: Email of creator
 * - createdAt: Timestamp when created (same as versionTimestamp)
 *
 * **Version Identification:**
 * versionLabel is the primary identifier for get/delete/update operations.
 * Must be unique within a platform/environment combination.
 * Format: Semantic versioning (e.g., "1.0.0", "2.1.0-beta.1")
 *
 * **Immutability:**
 * Once created, versions cannot be modified. To fix errors, create a new version.
 * Only the isStable flag can be changed via separate endpoint.
 */
export const VersionSchema = z.object({
  platform: z.string(),
  environment: z.string(),
  versionLabel: z.string().min(1, 'Version label is required'),
  versionTimestamp: z.string().datetime(),
  isStable: z.boolean().default(false),
  config: ConfigSchema,
  createdBy: z.string().email(),
  createdAt: z.string().datetime(),
});

/**
 * Schema for creating a new version (omits auto-generated fields).
 *
 * @remarks
 * versionTimestamp and createdAt are auto-generated by the service.
 * Users must provide platform, environment, versionLabel, and config.
 *
 * **Required Fields:**
 * - platform: Platform identifier
 * - environment: Environment name
 * - versionLabel: Semantic version (e.g., "1.0.0") - used as primary identifier
 * - config: Configuration payload
 * - createdBy: Creator email
 *
 * **Optional Fields:**
 * - isStable: Whether this version is production-ready (default: false)
 */
export const CreateVersionSchema = VersionSchema.omit({
  versionTimestamp: true,
  createdAt: true,
});

/**
 * Schema for cache invalidation requests.
 *
 * @remarks
 * Supports different levels of granularity:
 * - global: true - Invalidate all caches
 * - platform only - Invalidate platform-level caches
 * - platform + environment - Invalidate environment-level caches
 * - platform + environment + version - Invalidate specific version
 */
export const CacheInvalidationSchema = z.object({
  platform: z.string().optional(),
  environment: z.string().optional(),
  version: z.string().optional(),
  global: z.boolean().optional(),
});

/** Configuration object type - flexible key-value structure */
export type Config = z.infer<typeof ConfigSchema>;

/** Configuration version type */
export type Version = z.infer<typeof VersionSchema>;

/** Create version request type */
export type CreateVersion = z.infer<typeof CreateVersionSchema>;

/** Cache invalidation request type */
export type CacheInvalidation = z.infer<typeof CacheInvalidationSchema>;
